package org.johnnymod.holdmyguns;

import net.fabricmc.api.ModInitializer;

public class Holdmyguns implements ModInitializer {

    // GENERATED BY INTELLIJ MINECRAFT DEV PLUGIN - IGNORE
    @Override
    public void onInitialize() {
    }
}
