package org.johnnymod.holdmyguns.client;

import net.fabricmc.fabric.api.datagen.v1.DataGeneratorEntrypoint;
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator;

public class HoldmygunsDataGenerator implements DataGeneratorEntrypoint {

    // GENERATED BY INTELLIJ MINECRAFT DEV PLUGIN - IGNORE
    @Override
    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
        FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();
    }
}
