package org.johnnymod.holdmyguns.client;

import net.fabricmc.api.ClientModInitializer;

public class HoldmygunsClient implements ClientModInitializer {

    // GENERATED BY INTELLIJ MINECRAFT DEV PLUGIN - IGNORE
    @Override
    public void onInitializeClient() {
    }
}
